# Generated by Django 3.2.9 on 2021-12-22 18:42

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('memberaudit', '0006_add_current_ship'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscordChannel',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('last_update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RelayConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_types', multiselectfield.db.fields.MultiSelectField(choices=[('AL', 'alliance'), ('CP', 'corporation')], help_text='Category of mails that you want to relay to Discord.', max_length=5)),
                ('ping_type', models.CharField(choices=[('PN', '(none)'), ('PH', '@here'), ('PE', '@everybody')], default='PN', help_text='Option to ping every member of the channel', max_length=2, verbose_name='channel pings')),
                ('is_enabled', models.BooleanField(default=True, help_text='toogle for activating or deactivating relaying mail')),
                ('channels', models.ManyToManyField(to='mailrelay.DiscordChannel')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memberaudit.character')),
            ],
        ),
    ]
