# Generated by Django 3.2.9 on 2021-12-25 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailrelay", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="relayconfig",
            name="channels",
        ),
        migrations.AddField(
            model_name="relayconfig",
            name="discord_channel",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="mailrelay.discordchannel",
            ),
        ),
    ]
