# Generated by Django 3.2.9 on 2021-12-22 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberaudit', '0006_add_current_ship'),
        ('mailrelay', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='relayconfig',
            name='mails_sent',
            field=models.ManyToManyField(related_name='_mailrelay_relayconfig_mails_sent_+', to='memberaudit.CharacterMail'),
        ),
    ]
