# Generated by Django 3.2.9 on 2021-12-26 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailrelay", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DiscordCategory",
            fields=[
                ("id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(db_index=True, max_length=255)),
                ("last_update_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name="discordchannel",
            name="category",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to="mailrelay.discordcategory",
            ),
        ),
    ]
