# Generated by Django 3.2.9 on 2021-12-27 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailrelay", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="relayconfig",
            name="last_relay_at",
        ),
        migrations.AddField(
            model_name="relayconfig",
            name="last_service_run_at",
            field=models.DateTimeField(
                default=None,
                editable=False,
                help_text="Time of last successful service run.",
                null=True,
            ),
        ),
    ]
