# Generated by Django 3.2.9 on 2021-12-23 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailrelay', '0002_relayconfig_mails_sent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relayconfig',
            name='notification_types',
        ),
        migrations.AddField(
            model_name='relayconfig',
            name='mail_category',
            field=models.CharField(choices=[('AL', 'Alliance mails'), ('CP', 'Corporation mails')], default='AL', help_text='Category of mails that you want to relay to Discord.', max_length=2),
            preserve_default=False,
        ),
    ]
