# Generated by Django 3.2.9 on 2021-12-26 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailrelay", "0002_auto_20211226_1848"),
    ]

    operations = [
        migrations.AlterField(
            model_name="discordchannel",
            name="category",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="channels",
                to="mailrelay.discordcategory",
            ),
        ),
    ]
