# Generated by Django 3.2.9 on 2021-12-23 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberaudit', '0006_add_current_ship'),
        ('mailrelay', '0003_auto_20211223_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relayconfig',
            name='mails_sent',
            field=models.ManyToManyField(editable=False, help_text='Latest mails that have already been sent', related_name='_mailrelay_relayconfig_mails_sent_+', to='memberaudit.CharacterMail'),
        ),
    ]
