# Generated by Django 3.2.9 on 2021-12-25 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailrelay", "0005_alter_relayconfig_mail_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="relayconfig",
            name="mail_category",
            field=models.CharField(
                choices=[
                    ("AL", "All mails"),
                    ("AM", "Alliance mails"),
                    ("CM", "Corporation mails"),
                ],
                help_text="Category of mails that you want to relay to Discord.",
                max_length=2,
            ),
        ),
    ]
